#!/bin/sh

echo "The following will need to be installed:"
echo "Tmux  Macchanger  Neofetch"

sleep 2

apt-get update && apt-get upgrade -y

apt-get install tmux -y && apt-get install macchanger -y  && apt-get install neofetch -y && apt-get install figlet -y

#git clone https://github.com/aircrack-ng/aircrack-ng
#cd aircrack-ng
#autoreconf -i
#./configure --with-experimental
#make
#make install
#ldconfig

echo "Installation Complete, Making executable..."
chmod +x OPNsesame
cp OPNsesame /usr/bin/
echo "Done"

